// quotes.js

const quotes = {
    "01": "[01] A fresh start is always a chance to shine!",
    "02": "[02] Hard work today leads to success tomorrow.",
    "03": "[03] Never stop believing in yourself.",
    "04": "[04] Great things take time. Keep going!",
    "05": "[05] Challenges make you stronger.",
    "06": "[06] Stay positive and make it happen.",
    "07": "[07] Each day is a new opportunity.",
    "08": "[08] Small steps lead to big achievements.",
    "09": "[09] Dream big, work hard!",
    "10": "[10] You are capable of amazing things.",
    "11": "[11] Keep moving forward, no matter what.",
    "12": "[12] Today is a gift, make it count.",
    "13": "[13] Stay strong, stay focused.",
    "14": "[14] Success starts with a single step.",
    "15": "[15] Push yourself to be the best version of you.",
    "16": "[16] Mistakes are proof that you're trying.",
    "17": "[17] Believe in the power of yet.",
    "18": "[18] The best time for new beginnings is now.",
    "19": "[19] A positive mindset brings positive things.",
    "20": "[20] You are stronger than you think.",
    "21": "[21] Progress, not perfection.",
    "22": "[22] Keep your eyes on the prize.",
    "23": "[23] Turn obstacles into opportunities.",
    "24": "[24] Strive for progress, not perfection.",
    "25": "[25] One step at a time.",
    "26": "[26] Hard work always pays off.",
    "27": "[27] Embrace the journey.",
    "28": "[28] Every day is a second chance.",
    "29": "[29] Make today worth remembering.",
    "30": "[30] Nothing is impossible with determination.",
    "31": "[31] Success is built daily."
};
